name: Publish release

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test

      - name: Determine release version
        id: determine_version
        run: echo ::set-output name=version::${{ github.ref_name }}

      - name: Build APK
        if: startsWith(steps.determine_version.outputs.version, 'v0.')
        run: flutter build apk --flavor pre-release --release
      - name: Build APK
        if: !startsWith(steps.determine_version.outputs.version, 'v0.')
        run: flutter build apk --release

      - name: Publish APK
        uses: actions/upload-artifact@v2
        with:
          name: Release APK
          path: build/app/outputs/flutter-apk/app-release.apk
