name: Publish APK Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.1'

      - name: Extract Version
        id: extract_version
        run: |
          version=$(echo "${{ github.event.head_commit.message }}" | grep -oP 'v\d+\.\d+\.\d+')
          if [[ -z "$version" ]]; then
            echo "No version found in commit message."
            exit 0
          fi
          echo "::set-output name=version::$version"

      - name: Create Git Tag
        run: git tag ${{ steps.extract_version.outputs.version }}
        if: steps.extract_version.outputs.version != ''

      - name: Push Git Tag
        run: git push origin ${{ steps.extract_version.outputs.version }}
        if: steps.extract_version.outputs.version != ''

      - name: Build APK
        run: flutter build apk --release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: Release ${{ steps.extract_version.outputs.version }}
          prerelease: true
