name: Publish APK Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.1'

      - name: Check version
        id: version
        run: echo "::set-output name=version::$(grep -oP 'v\d+\.\d+\.\d+' pubspec.yaml)"

      - name: Build APK
        run: flutter build apk --release

      - name: Publish Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ steps.version.outputs.version }}
        with:
          artifacts: build/app/outputs/flutter-apk/app-release.apk
