name: Publish APK Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.1'

      - name: Extract Version
        id: extract_version
        run: |
          version=$(sed -nE 's/version:\s*([0-9]+\.[0-9]+\.[0-9]+)/\1/p' pubspec.yaml)
          echo "::set-output name=version::$version"

      - name: Create Git Tag
        run: git tag ${{ steps.extract_version.outputs.version }}
        if: startsWith(github.event.head_commit.message, 'Version:')

      - name: Push Git Tag
        run: git push origin ${{ steps.extract_version.outputs.version }}
        if: startsWith(github.event.head_commit.message, 'Version:')

      - name: Build APK
        run: flutter build apk --release

      - name: Publish Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          tag: ${{ steps.extract_version.outputs.version }}
